[project]
name = "mist-medical"
version = "0.1.6-beta"
requires-python = ">= 3.8"
description = "MIST is a simple and scalable end-to-end framework for medical imaging segmentation."
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    {name = "Adrian Celaya", email = "aecelaya@rice.edu"},
    {name = "David Fuentes", email = "dtfuentes@mdanderson.org"},
    {name = "Beatrice Riviere", email = "riviere@rice.edu"},
    {name = "Rice University"},
    {name = "The University of Texas MD Anderson Cancer Center"}
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Medical Science Apps."
]
keywords = [
    "deep learning",
    "image segmentation",
    "semantic segmentation",
    "medical image analysis",
    "medical image segmentation",
    "nnUNet",
    "U-Net",
    "vision transformers",
    "Swin UNETR"
]
dynamic = ["dependencies"]

[project.urls]
homepage = "https://github.com/mist-medical/MIST"
repository = "https://github.com/mist-medical/MIST"
documentation = "https://mist-medical.readthedocs.io/"

[project.scripts]
mist_run_all = "mist.scripts.run_all_entrypoint:run_all_entry"
mist_analyze = "mist.scripts.analyze_entrypoint:analyze_entry"
mist_preprocess = "mist.scripts.preprocess_entrypoint:preprocess_entry"
mist_train = "mist.scripts.train_entrypoint:train_entry"
mist_predict = "mist.predict:mist_predict_entry"
mist_evaluate = "mist.eval_preds:mist_eval_entry"
mist_postprocess = "mist.post_preds:mist_postprocess_entry"
mist_convert_dataset = "mist.convert_to_mist:convert_to_mist_entry"

[tool.codespell]
skip = ".git"

[build-system]
requires = ["setuptools", "wheel", "pip"]
build-backend = "setuptools.build_meta"

[tool.dependencies-dev]
pytest = "^7.0"
flake8 = "^6.0"
black = "^23.0"
mypy = "^1.0"
