# Copyright (c) MIST Imaging LLC.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Run Tests and Generate Coverage Badge

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov coverage-badge

    - name: Run tests and generate coverage report
      run: |
        pytest --cov=mist --cov-report=term-missing --cov-report=xml
        coverage-badge -o coverage.svg -f

    - name: Upload coverage badge
      uses: actions/upload-artifact@v4
      with:
        name: coverage-badge
        path: coverage.svg

    - name: Commit coverage badge to repo (optional)
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add coverage.svg
        git commit -m "Update coverage badge"
        git push
      continue-on-error: true
